name: Build Caddy on New Release

on:
  release:
    types:
      - published  # Trigger the workflow on new release publication
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the build environment
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Go (latest stable version)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install xcaddy for custom builds
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build Caddy with custom plugins
        run: |
          xcaddy build --with github.com/caddy-dns/cloudflare --with github.com/caddyserver/replace-response

      - name: Upload Caddy binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: caddy-binary
          path: caddy

      - name: Generate Release Tag
        id: generate_string
        run: |
          # Get the current date and time in the format "YYYY-MM-DD-HHMMSS"
          release_tag="release-$(date '+%Y-%m-%d-%H%M%S')"
          # Store the release string in an output variable
          echo "release_tag=$release_tag" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.release_tag }}
          files: caddy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
